version: "3.9"

services:
  greennote-db:
    image: postgres:15
    container_name: greennote-db
    environment:
      POSTGRES_USER: greennote
      POSTGRES_PASSWORD: greennote
      POSTGRES_DB: greennote
    ports:
      - "5432:5432"
    volumes:
      - greennote-db-data:/var/lib/postgresql/data

  greennote-kafka:
    image: bitnami/kafka:3.7
    container_name: greennote-kafka
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@greennote-kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://greennote-kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  greennote-minio:
    image: minio/minio:RELEASE.2024-01-31T20-20-33Z
    container_name: greennote-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - greennote-minio-data:/data

  greennote-service:
    build:
      context: .
      dockerfile: services/greennote-service/Dockerfile
    container_name: greennote-service
    depends_on:
      - greennote-db
      - greennote-kafka
      - greennote-minio
    environment:
      GREENNOTE_GRPC_PORT: "50051"
      GREENNOTE_HTTP_PORT: "8080"
      GREENNOTE_DATABASE_URL: "postgres://greennote:greennote@greennote-db:5433/greennote?sslmode=disable"
      KAFKA_BROKERS: "greennote-kafka:9092"
      GREENNOTE_KAFKA_TOPIC_APPROVED: "greennote.approved"
      MINIO_ENDPOINT: "greennote-minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "greennote-docs"
      MINIO_USE_SSL: "false"
    ports:
      - "50051:50051"
      - "8080:8080"

volumes:
  greennote-db-data:
  greennote-minio-data:
